Ryan/autokit cm4
balena-os/leviathan-worker pull request #113
Opened 2024-06-11 12:15 UTC by rcooke-warwick

2024-06-14 14:02 UTC, alexgg requested changes

2024-06-14 14:02 UTC, alexgg commented on package-lock.json
The title of this commit is misleading - it's really dependencies update. I don't think we should mention the cm4 even if its the main driver for the update.

2024-06-14 15:58 UTC, rcooke-warwick commented on package-lock.json
agreed and changed

2024-06-17 09:07 UTC, alexgg approved these changes

2024-06-17 09:07 UTC, merged